repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
    -   id: ruff-check
        args: [ --fix, --extend-select=I ]
    -   id: ruff-format
- repo: local
  hooks:
    -   id: ty
        name: ty check
        entry: uv run ty check .
        language: python
        pass_filenames: false
        always_run: true
- repo: https://github.com/gitguardian/ggshield
  rev: v1.48.0
  hooks:
    -   id: ggshield
        language_version: python3
